apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ngo-service
  namespace: argocd
  labels:
    project: solidarytech
    environment: production
spec:
  project: default
  source:
    repoURL: https://github.com/marialeticiacs/fiap-hackathon-fase-5
    targetRevision: main
    path: k8s/base/ngo-service
  destination:
    server: https://kubernetes.default.svc
    namespace: solidarytech
  syncPolicy:
    automated:
      prune: true       # remove recursos deletados do Git
      selfHeal: true    # corrige drift automático
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true