apiVersion: apps/v1
kind: Deployment
metadata:
  name: donation-service
  namespace: solidarytech
  labels:
    app: donation-service
    criticality: hot-path
    version: "1.0.0"
    project: solidarytech
spec:
  replicas: 3          # HOT PATH — inicia com mais réplicas
  selector:
    matchLabels:
      app: donation-service
  template:
    metadata:
      labels:
        app: donation-service
        criticality: hot-path
        version: "1.0.0"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8082"
        prometheus.io/path: "/health"
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: donation-service
      containers:
        - name: donation-service
          image: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/solidarytech/donation-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: PORT
              value: "8082"
            - name: AWS_REGION
              value: "us-east-1"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: solidarytech-secrets
                  key: DATABASE_URL
            - name: AWS_SQS_URL
              valueFrom:
                secretKeyRef:
                  name: solidarytech-secrets
                  key: SQS_QUEUE_URL
          # HOT PATH — recursos maiores
          resources:
            requests:
              cpu: "200m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3