apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: donation-service-hpa
  namespace: solidarytech
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: donation-service
  minReplicas: 3       # HOT PATH — mínimo maior
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60    # threshold menor = escala mais cedo
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30   # escala rápido no pico
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300  # escala devagar ao baixar
      policies:
        - type: Pods
          value: 1
          periodSeconds: 120