apiVersion: v1
kind: Secret
metadata:
  name: solidarytech-secrets
  namespace: solidarytech
type: Opaque
stringData:
  # Pegar do output do Terraform: terraform output rds_endpoint
  DATABASE_URL: "postgresql://solidarytech_admin:<SENHA>@<RDS_ENDPOINT>:5432/solidarytech"
  # Pegar do output: terraform output redis_endpoint
  REDIS_URL: "rediss://<REDIS_ENDPOINT>:6379"
  # Pegar do output: terraform output sqs_queue_url
  SQS_QUEUE_URL: "https://sqs.us-east-1.amazonaws.com/<ACCOUNT_ID>/solidarytech-production-donations"